/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  DB: D1Database;
  ANNOTATIONS_BUCKET: R2Bucket;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Expose Cloudflare bindings and origin to app-router route handlers
    globalThis.__env = env;
    globalThis.__origin = new URL(request.url).origin;

    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Delegate everything else to vinext
    const response = await handler.fetch(request);

    // Fix React Fizz emitting invalid <link rel="preload" as="stylesheet">
    const contentType = response.headers.get("content-type") || "";
    if (contentType.includes("text/html") && response.body) {
      const text = await response.text();
      const fixed = text.replace(
        /<link(?=[^>]*\srel="preload")[^>]*>/g,
        (tag) => tag.replace(' as="stylesheet"', ' as="style"')
      );
      return new Response(fixed, {
        status: response.status,
        statusText: response.statusText,
        headers: response.headers,
      });
    }

    return response;
  },
};
